[tool.isort]
known_first_party = ["ibllib", "iblutil", "one", "brainbox"]
known_local_folder = ["neurencoding"]
import_heading_stdlib = "Standard library"
import_heading_thirdparty = "Third party libraries"
import_heading_firstparty = "IBL libraries"
import_heading_localfolder = "Neurencoding repo imports"
